/**
 * Downloader - ENM Dump (multiple ENMs, user/pwd per ENM)
 * Command: cmedit export -n *_SP or site1;site2;... --filetype 3GPP -jn downloader_YYYYMMDD_HHMMSS -f file:mos_downloader.txt
 * Site list: load file generated by update_site_list.py (TSV: Regional, UF, MUNICIPIO, SiteID, Tech)
 */

const STORAGE_PROFILES = 'downloader_enm_profiles';
const STORAGE_LAST_OUTPUT_DIR = 'downloader_last_output_dir';
const STORAGE_SITE_LIST_SAVE_DIR = 'downloader_site_list_save_dir';
const STORAGE_PARSER_INPUT = 'downloader_parser_input_dir';
const STORAGE_PARSER_OUTPUT = 'downloader_parser_output_dir';
const STORAGE_PARSER_CELLREF = 'downloader_parser_cellref_dir';
const STORAGE_PARSER_ENRICHED = 'downloader_parser_enriched_dir';
const STORAGE_FILE_VIEWER_OUTPUT = 'downloader_file_viewer_output_dir';
const STORAGE_CUSTOMIZE_TXTS = 'downloader_customize_txts';

/** Loaded site list (from sites_list.txt or built from folder). Array of { Regional, UF, MUNICIPIO, SiteID, Tech } */
let siteListData = [];
let siteListLoadedFromFile = false;
let selectedMunicipalities = [];
let siteListBusy = false;

const ENM_SERVERS = {
  'ENMBARB': 'https://enmbarb.ran.redestlf.br/',
  'ENMBARA': 'https://enmbara.ran.redestlf.br/',
  'ENMCTPB': 'https://enmctpb.ran.redestlf.br/',
  'ENMCTPA': 'https://enmctpa.ran.redestlf.br/'
};

/** ENM order in table (short name for job: ENMBARA -> BARA) */
const ENM_IDS = ['ENMBARA', 'ENMBARB', 'ENMCTPB', 'ENMCTPA'];

function enmShortName(id) {
  return id.replace(/^ENM/, '');
}

const AVAILABLE_UFS = ['AM', 'AP', 'BA', 'MA', 'MG', 'PA', 'RR', 'SE', 'SP'];

// MOs aligned with script 3: conversion only processes those present in the dump
const DEFAULT_MOS = [
  { id: 'EUtranCellRelation', pattern: 'EUtranCellRelation.*;', desc: 'LTE Neighbor Relations' },
  { id: 'EUtranCellFDD', pattern: 'EUtranCellFDD.*;', desc: 'LTE FDD Cells' },
  { id: 'EUtranCellTDD', pattern: 'EUtranCellTDD.*;', desc: 'LTE TDD Cells' },
  { id: 'ENodeBFunction', pattern: 'ENodeBFunction.*;', desc: 'eNodeB Functions' },
  { id: 'ExternalEUtranCellFDD', pattern: 'ExternalEUtranCellFDD.*;', desc: 'External LTE FDD' },
  { id: 'ExternalEUtranCellTDD', pattern: 'ExternalEUtranCellTDD.*;', desc: 'External LTE TDD' },
  { id: 'UtranFreqRelation', pattern: 'UtranFreqRelation.*;', desc: 'Utran Freq Relation' },
  { id: 'RetSubUnit', pattern: 'RetSubUnit.*;', desc: 'Ret Sub Unit' },
  { id: 'EUtranFreqRelation', pattern: 'EUtranFreqRelation.*;', desc: 'LTE Freq Relation' },
  { id: 'TermPointToMme', pattern: 'TermPointToMme.*;', desc: 'Term Point To MME' },
  { id: 'ReportConfigSearch', pattern: 'ReportConfigSearch.*;', desc: 'Report Config Search' },
  { id: 'ReportConfigEUtraInterFreqLb', pattern: 'ReportConfigEUtraInterFreqLb.*;', desc: 'Report Config EUtra Inter Freq Lb' },
  { id: 'ReportConfigA5', pattern: 'ReportConfigA5.*;', desc: 'Report Config A5' },
  { id: 'ReportConfigA5UlTrig', pattern: 'ReportConfigA5UlTrig.*;', desc: 'Report Config A5 UL Trig' },
  { id: 'SectorCarrier', pattern: 'SectorCarrier.*;', desc: 'Sector Carrier' },
  { id: 'LoadBalancingFunction', pattern: 'LoadBalancingFunction.*;', desc: 'Load Balancing Function' },
  { id: 'QciProfilePredefined', pattern: 'QciProfilePredefined.*;', desc: 'QCI Profile Predefined' },
  { id: 'GigaBitEthernet', pattern: 'GigaBitEthernet.*;', desc: 'GigaBit Ethernet' },
  { id: 'EthernetPort', pattern: 'EthernetPort.*;', desc: 'Ethernet Port' },
  { id: 'FeatureState', pattern: 'FeatureState.*;', desc: 'Feature State' },
  { id: 'OptionalFeatureLicense', pattern: 'OptionalFeatureLicense.*;', desc: 'Optional Feature License' },
  { id: 'ReportConfigB2Utra', pattern: 'ReportConfigB2Utra.*;', desc: 'Report Config B2 Utra' },
  { id: 'DataRadioBearer', pattern: 'DataRadioBearer.*;', desc: 'Data Radio Bearer' },
  { id: 'SignalingRadioBearer', pattern: 'SignalingRadioBearer.*;', desc: 'Signaling Radio Bearer' },
  { id: 'EUtranFrequency', pattern: 'EUtranFrequency.*;', desc: 'LTE Frequency' },
  { id: 'CarrierAggregationFunction', pattern: 'CarrierAggregationFunction.*;', desc: 'Carrier Aggregation Function' },
  { id: 'AdmissionControl', pattern: 'AdmissionControl.*;', desc: 'Admission Control' },
  { id: 'AnrFunctionEUtran', pattern: 'AnrFunctionEUtran.*;', desc: 'ANR Function EUtran' },
  { id: 'AnrFunction', pattern: 'AnrFunction.*;', desc: 'ANR Function' },
  { id: 'AnrFunctionUtran', pattern: 'AnrFunctionUtran.*;', desc: 'ANR Function Utran' },
  { id: 'NbIotCell', pattern: 'NbIotCell.*;', desc: 'NB-IoT Cell' },
  { id: 'Router', pattern: 'Router.*;', desc: 'Router' },
  { id: 'InterfaceIPv4', pattern: 'InterfaceIPv4.*;', desc: 'Interface IPv4' },
  { id: 'InterfaceIPv6', pattern: 'InterfaceIPv6.*;', desc: 'Interface IPv6' },
  { id: 'Paging', pattern: 'Paging.*;', desc: 'Paging' },
  { id: 'ReportConfigA1Prim', pattern: 'ReportConfigA1Prim.*;', desc: 'Report Config A1 Prim' },
  { id: 'ReportConfigA1Sec', pattern: 'ReportConfigA1Sec.*;', desc: 'Report Config A1 Sec' },
  { id: 'ReportConfigB1Geran', pattern: 'ReportConfigB1Geran.*;', desc: 'Report Config B1 Geran' },
  { id: 'ReportConfigB1Utra', pattern: 'ReportConfigB1Utra.*;', desc: 'Report Config B1 Utra' },
  { id: 'ReportConfigB1GUtra', pattern: 'ReportConfigB1GUtra.*;', desc: 'Report Config B1 GUtra' },
  { id: 'ReportConfigB1NR', pattern: 'ReportConfigB1NR.*;', desc: 'Report Config B1 NR' },
  { id: 'ReportConfigEUtraBadCovPrim', pattern: 'ReportConfigEUtraBadCovPrim.*;', desc: 'Report Config EUtra Bad Cov Prim' },
  { id: 'ReportConfigEUtraBadCovSec', pattern: 'ReportConfigEUtraBadCovSec.*;', desc: 'Report Config EUtra Bad Cov Sec' },
  { id: 'ReportConfigEUtraBestCell', pattern: 'ReportConfigEUtraBestCell.*;', desc: 'Report Config EUtra Best Cell' },
  { id: 'ReportConfigA5UlTraffic', pattern: 'ReportConfigA5UlTraffic.*;', desc: 'Report Config A5 UL Traffic' },
  { id: 'ReportConfigSCellA1A2', pattern: 'ReportConfigSCellA1A2.*;', desc: 'Report Config SCell A1 A2' },
  { id: 'DrxProfile', pattern: 'DrxProfile.*;', desc: 'DRX Profile' },
  { id: 'Rrc', pattern: 'Rrc.*;', desc: 'RRC' },
  { id: 'UeMeasControl', pattern: 'UeMeasControl.*;', desc: 'UE Meas Control' },
  { id: 'Rcs', pattern: 'Rcs.*;', desc: 'RCS' },
  { id: 'ManagedElement', pattern: 'ManagedElement.*;', desc: 'Managed Element' },
  { id: 'AddressIPv4', pattern: 'AddressIPv4.*;', desc: 'Address IPv4' },
  { id: 'Slot', pattern: 'Slot.*;', desc: 'Slot' },
  { id: 'CellSleepFunction', pattern: 'CellSleepFunction.*;', desc: 'Cell Sleep Function' },
  { id: 'ExternalENodeBFunction', pattern: 'ExternalENodeBFunction.*;', desc: 'External eNodeB Function' },
  { id: 'GUtranCellRelation', pattern: 'GUtranCellRelation.*;', desc: 'GUtran Cell Relation' },
  { id: 'GUtranFreqRelation', pattern: 'GUtranFreqRelation.*;', desc: 'GUtran Freq Relation' },
  { id: 'ReportConfigA4', pattern: 'ReportConfigA4.*;', desc: 'Report Config A4' },
  { id: 'ReportConfigA5Anr', pattern: 'ReportConfigA5Anr.*;', desc: 'Report Config A5 Anr' },
  { id: 'ReportConfigA5DlComp', pattern: 'ReportConfigA5DlComp.*;', desc: 'Report Config A5 Dl Comp' },
  { id: 'ReportConfigB2Geran', pattern: 'ReportConfigB2Geran.*;', desc: 'Report Config B2 Geran' },
  { id: 'AnrFunctionGeran', pattern: 'AnrFunctionGeran.*;', desc: 'ANR Function Geran' },
  { id: 'SystemFunctions', pattern: 'SystemFunctions.*;', desc: 'System Functions' },
  { id: 'CapacityState', pattern: 'CapacityState.*;', desc: 'Capacity State' },
  { id: 'TermPointToENodeB', pattern: 'TermPointToENodeB.*;', desc: 'Term Point To ENodeB' },
  { id: 'TermPointToENB', pattern: 'TermPointToENB.*;', desc: 'Term Point To ENB' },
  { id: 'TermPointToGNBCUCP', pattern: 'TermPointToGNBCUCP.*;', desc: 'Term Point To GNBCUCP' },
  { id: 'TermPointToGNBDU', pattern: 'TermPointToGNBDU.*;', desc: 'Term Point To GNBDU' },
  { id: 'TermPointToAmf', pattern: 'TermPointToAmf.*;', desc: 'Term Point To Amf' },
  { id: 'TermPointToGNB', pattern: 'TermPointToGNB.*;', desc: 'Term Point To GNB' },
  { id: 'TermPointToGNodeB', pattern: 'TermPointToGNodeB.*;', desc: 'Term Point To GNodeB' },
  { id: 'GNBCUCPFunction', pattern: 'GNBCUCPFunction.*;', desc: 'GNB CUCP Function' },
  { id: 'GNBCUUPFunction', pattern: 'GNBCUUPFunction.*;', desc: 'GNB CUUP Function' },
  { id: 'GNBDUFunction', pattern: 'GNBDUFunction.*;', desc: 'GNB DU Function' },
  { id: 'NRCellCU', pattern: 'NRCellCU.*;', desc: 'NR Cell CU' },
  { id: 'NRCellDU', pattern: 'NRCellDU.*;', desc: 'NR Cell DU' },
  { id: 'SharingGroup', pattern: 'SharingGroup.*;', desc: 'Sharing Group' },
  { id: 'NRFreqRelation', pattern: 'NRFreqRelation.*;', desc: 'NR Freq Relation' },
  { id: 'NRCellRelation', pattern: 'NRCellRelation.*;', desc: 'NR Cell Relation' },
  { id: 'NRSectorCarrier', pattern: 'NRSectorCarrier.*;', desc: 'NR Sector Carrier' },
  { id: 'CommonBeamforming', pattern: 'CommonBeamforming.*;', desc: 'Common Beamforming' },
  { id: 'RadioEquipmentClockReference', pattern: 'RadioEquipmentClockReference.*;', desc: 'Radio Equipment Clock Reference' },
  { id: 'AnrFunctionNR', pattern: 'AnrFunctionNR.*;', desc: 'ANR Function NR' },
  { id: 'CUUP5qi', pattern: 'CUUP5qi.*;', desc: 'CUUP 5qi' },
  { id: 'ExternalGNodeBFunction', pattern: 'ExternalGNodeBFunction.*;', desc: 'External GNodeB Function' },
  { id: 'ExternalGUtranCell', pattern: 'ExternalGUtranCell.*;', desc: 'External GUtran Cell' },
  { id: 'McfbCellProfileUeCfg', pattern: 'McfbCellProfileUeCfg.*;', desc: 'Mcfb Cell Profile UE Cfg' },
  { id: 'ExternalNRCellCU', pattern: 'ExternalNRCellCU.*;', desc: 'External NR Cell CU' },
  { id: 'UeMCEUtranFreqRelProfileUeCfg', pattern: 'UeMCEUtranFreqRelProfileUeCfg.*;', desc: 'UE MC EUtran Freq Rel Profile UE Cfg' }
];

let customMos = [];

const MOB_MOS = [
  'EUtranCellFDD', 'EUtranCellTDD', 'ENodeBFunction', 'EUtranCellRelation',
  'GUtranCellRelation', 'GUtranFreqRelation', 'ExternalGUtranCell', 'AddressIPv4',
  'NRCellCU', 'NRCellDU', 'NRCellRelation', 'TermPointToGNodeB', 'TermPointToENodeB',
  'TermPointToGNB', 'GNBCUCPFunction', 'ManagedElement', 'ExternalNRCellCU'
];

// ---------- Site list ----------
/** Parse one CSV line (handles quoted fields for PT-BR data). */
function parseCSVLine(line) {
  const out = [];
  let i = 0;
  while (i < line.length) {
    if (line[i] === '"') {
      i++;
      let s = '';
      while (i < line.length && line[i] !== '"') {
        s += line[i];
        if (line[i] === '"' && line[i + 1] === '"') { s += '"'; i += 2; continue; }
        i++;
      }
      if (line[i] === '"') i++;
      out.push(s.trim());
      if (line[i] === ',') i++;
    } else {
      let s = '';
      while (i < line.length && line[i] !== ',') s += line[i++];
      out.push(s.trim());
      if (line[i] === ',') i++;
    }
  }
  return out;
}

/** Parse CSV text (first line = header). Encoding should already be applied by FileReader. */
function parseCSV(text) {
  const lines = text.split(/\r?\n/).filter(l => l.length > 0);
  if (lines.length < 2) return [];
  const header = parseCSVLine(lines[0]);
  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    const cells = parseCSVLine(lines[i]);
    const row = {};
    header.forEach((h, j) => { row[h] = (cells[j] || '').trim(); });
    rows.push(row);
  }
  return rows;
}

/** Read file as text with encoding (ISO-8859-1 for PT-BR CSVs). */
function readFileAsText(file, encoding) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = () => reject(reader.error);
    reader.readAsText(file, encoding || 'ISO-8859-1');
  });
}

function getSiteListSaveDir() {
  const configured = (document.getElementById('site-list-folder-path') && document.getElementById('site-list-folder-path').value || '').trim();
  // Ignore old UI summary text from previous versions.
  if (configured && !/files selected\s*\(/i.test(configured)) return configured;
  return 'C:/Downloader/cellref';
}

function dirnamePath(p) {
  const s = String(p || '').replace(/\\/g, '/');
  const i = s.lastIndexOf('/');
  return i > 0 ? s.slice(0, i) : '';
}

function commonPath(paths) {
  if (!paths.length) return '';
  const split = paths.map(p => p.replace(/\\/g, '/').split('/').filter(Boolean));
  const minLen = Math.min(...split.map(a => a.length));
  const out = [];
  for (let i = 0; i < minLen; i++) {
    const token = split[0][i];
    if (split.every(a => a[i].toLowerCase() === token.toLowerCase())) out.push(token);
    else break;
  }
  if (!out.length) return '';
  const first = paths[0].replace(/\\/g, '/');
  const hasDrive = /^[A-Za-z]:\//.test(first);
  return (hasDrive ? '' : '/') + out.join('/');
}

function inferBaseDirFromSelectedFiles(fileList) {
  const files = Array.from(fileList || []);
  if (!files.length) return '';
  // Works in environments that expose file.path (Electron/desktop shells).
  const fullDirs = files
    .map(f => dirnamePath(f.path || ''))
    .filter(Boolean);
  if (fullDirs.length) {
    const cp = commonPath(fullDirs);
    return cp || fullDirs[0];
  }
  return '';
}

async function saveSiteListToServer(rows) {
  const saveDir = getSiteListSaveDir();
  const response = await fetch('http://127.0.0.1:8765/api/save-site-list', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ rows, save_dir: saveDir })
  });
  if (!response.ok) {
    const errText = await response.text();
    throw new Error(errText || `Could not save site list (${response.status}).`);
  }
  return response.json();
}

async function tryAutoLoadSiteListFromBaseDir(silentIfMissing = true) {
  const baseDir = getSiteListSaveDir();
  if (!baseDir) return false;
  try {
    const response = await fetch('http://127.0.0.1:8765/api/load-site-list', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ base_dir: baseDir })
    });
    if (!response.ok) {
      if (!silentIfMissing) {
        const msg = await response.text();
        showEnmResult('warning', `Could not auto-load site list from ${baseDir}: ${msg || response.statusText}`);
      }
      return false;
    }
    const data = await response.json();
    if (!data || !data.ok || !Array.isArray(data.rows)) return false;
    siteListData = dedupeAndSortSiteRows(data.rows);
    siteListLoadedFromFile = siteListData.length > 0;
    const statusEl = document.getElementById('site-list-status');
    if (statusEl) statusEl.innerHTML = `<span class="text-success">Auto-loaded ${siteListData.length} sites from ${data.path}.</span>`;
    refreshScopeUfControls();
    return true;
  } catch (_) {
    return false;
  }
}

function setSiteListBusy(isBusy, message) {
  siteListBusy = !!isBusy;
  const btn = document.getElementById('btn-update-site-list');
  const statusEl = document.getElementById('site-list-status');
  if (btn) {
    btn.disabled = !!isBusy;
    btn.innerHTML = isBusy
      ? '<span class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>Uploading...'
      : '<i class="bi bi-folder2-open"></i> Select files and update';
  }
  if (statusEl && message) {
    statusEl.innerHTML = `<span class="text-muted">${message}</span>`;
  }
}

/** Build site list from CSV files (LTE + NR), dedupe. */
async function updateSiteListFromFolder(files) {
  const fileList = Array.from(files || []);
  if (!fileList.length) {
    showEnmResult('warning', 'Select one or more source files first.');
    return;
  }
  setSiteListBusy(true, `Uploading ${fileList.length} file(s)...`);

  // Preferred path: backend smart parser (supports CSV/TXT/XLSX/XLS and delimiter detection).
  try {
    const formData = new FormData();
    fileList.forEach(f => formData.append('files', f, f.name));
    const response = await fetch('http://127.0.0.1:8765/api/update-site-list', {
      method: 'POST',
      body: formData
    });
    if (response.ok) {
      const data = await response.json();
      if (data && data.ok && Array.isArray(data.rows)) {
        const incoming = dedupeAndSortSiteRows(data.rows);
        siteListData = mergeSiteListRows(siteListData, incoming);
        siteListLoadedFromFile = siteListData.length > 0;
        const statusEl = document.getElementById('site-list-status');
        if (statusEl) statusEl.innerHTML = `<span class="text-success">Updated: +${incoming.length} site(s), total ${siteListData.length}.</span>`;
        refreshScopeUfControls();

        const warnings = Array.isArray(data.warnings) ? data.warnings : [];
        const sources = Array.isArray(data.sources) ? data.sources : [];
        const summary = sources.length ? ` Sources: ${sources.join(' | ')}` : '';
        const warnSummary = warnings.length ? ` Warnings: ${warnings.slice(0, 3).join(' | ')}` : '';
        setSiteListBusy(true, 'Processing and saving site list...');
        try {
          const saved = await saveSiteListToServer(siteListData);
          if (statusEl) statusEl.innerHTML = `<span class="text-success">Updated: +${incoming.length} site(s), total ${siteListData.length}. Saved: ${saved.path}</span>`;
          showEnmResult('success', `Site list updated: +${incoming.length} site(s), total ${siteListData.length}. Saved to ${saved.path}.${summary}${warnSummary}`);
        } catch (saveErr) {
          if (statusEl) statusEl.innerHTML = `<span class="text-danger">Updated in memory, but save failed: ${saveErr.message}</span>`;
          showEnmResult('warning', `Site list updated in memory: +${incoming.length} site(s), total ${siteListData.length}, but could not save file: ${saveErr.message}${summary}${warnSummary}`);
        }
        setSiteListBusy(false);
        return;
      }
    }
  } catch (_) {
    // If backend is unavailable, fallback to local CSV/TXT parser below.
  }

  // Fallback path: local browser parsing (CSV/TXT only, legacy behavior).
  const lteFile = Array.from(files).find(f => f.name === 'EUtranCell_TDD_FDD.csv');
  const nrFiles = Array.from(files).filter(f => f.name.startsWith('Cellref_5G') && (f.name.endsWith('.csv') || f.name.endsWith('.txt')));
  if (!lteFile && nrFiles.length === 0) {
    setSiteListBusy(false);
    showEnmResult('warning', 'No compatible files found. Select EUtranCell_TDD_FDD and/or Cellref_5G files.');
    return;
  }
  const seen = new Set();
  const outRows = [];
  const enc = 'ISO-8859-1';

  if (lteFile) {
    const text = await readFileAsText(lteFile, enc);
    const data = parseCSV(text);
    for (const r of data) {
      const regional = (r.Regional || '').trim();
      const uf = (r.UF || '').trim().toUpperCase();
      const municipio = (r.MUNICIPIO || '').trim();
      const siteId = (r.eNB || '').trim();
      if (!siteId) continue;
      const key = regional + '\t' + uf + '\t' + municipio + '\t' + siteId + '\tLTE';
      if (seen.has(key)) continue;
      seen.add(key);
      outRows.push({ Regional: regional, UF: uf, MUNICIPIO: municipio, SiteID: siteId, Tech: 'LTE' });
    }
  }
  for (const file of nrFiles) {
    const text = await readFileAsText(file, enc);
    let data = file.name.endsWith('.csv') ? parseCSV(text) : parseSiteListTSV(text);
    if (!data.length && text.includes('\t')) data = parseSiteListTSV(text);
    for (const r of data) {
      const regional = (r.Regional || '').trim();
      const uf = (r.UF || '').trim().toUpperCase();
      const municipio = (r.MUNICIPIO || '').trim();
      const siteId = (r.SiteID || r.SiteId || '').trim();
      if (!siteId) continue;
      const key = regional + '\t' + uf + '\t' + municipio + '\t' + siteId + '\tNR';
      if (seen.has(key)) continue;
      seen.add(key);
      outRows.push({ Regional: regional, UF: uf, MUNICIPIO: municipio, SiteID: siteId, Tech: 'NR' });
    }
  }

  const incoming = dedupeAndSortSiteRows(outRows);
  siteListData = mergeSiteListRows(siteListData, incoming);
  siteListLoadedFromFile = siteListData.length > 0;
  const statusEl = document.getElementById('site-list-status');
  if (statusEl) statusEl.innerHTML = `<span class="text-success">Updated: +${incoming.length} site(s), total ${siteListData.length}.</span>`;
  refreshScopeUfControls();
  try {
    setSiteListBusy(true, 'Processing and saving site list...');
    const saved = await saveSiteListToServer(siteListData);
    if (statusEl) statusEl.innerHTML = `<span class="text-success">Updated: +${incoming.length} site(s), total ${siteListData.length}. Saved: ${saved.path}</span>`;
    showEnmResult('success', `Site list updated (local fallback): +${incoming.length} site(s), total ${siteListData.length}. Saved to ${saved.path}.`);
  } catch (saveErr) {
    if (statusEl) statusEl.innerHTML = `<span class="text-danger">Updated in memory, but save failed: ${saveErr.message}</span>`;
    showEnmResult('warning', `Site list updated (local fallback): +${incoming.length} site(s), total ${siteListData.length}, but could not save file: ${saveErr.message}`);
  } finally {
    setSiteListBusy(false);
  }
}

function parseSiteListTSV(text) {
  const raw = (text || '').replace(/^\uFEFF/, '').trim();
  const lines = raw.split(/\r?\n/).filter(l => l.trim());
  if (lines.length < 2) return [];
  const header = lines[0].split('\t').map(h => h.trim());
  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    const cells = lines[i].split('\t');
    const row = {};
    header.forEach((h, j) => { row[h] = (cells[j] || '').trim(); });
    rows.push(row);
  }
  return rows;
}

function normalizeText(v) {
  return String(v || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
    .toUpperCase();
}

function normalizeSiteRow(row) {
  const techRaw = String((row && row.Tech) || '').trim().toUpperCase();
  let tech = techRaw;
  if (techRaw === '4G') tech = 'LTE';
  if (techRaw === '5G') tech = 'NR';
  return {
    Regional: String((row && row.Regional) || '').trim(),
    UF: String((row && row.UF) || '').trim().toUpperCase(),
    MUNICIPIO: String((row && row.MUNICIPIO) || '').trim(),
    SiteID: String((row && row.SiteID) || '').trim(),
    Tech: tech || 'LTE'
  };
}

function dedupeAndSortSiteRows(rows) {
  const out = [];
  const seen = new Set();
  (rows || []).forEach(r => {
    const row = normalizeSiteRow(r || {});
    if (!row.UF || !row.MUNICIPIO || !row.SiteID) return;
    const key = [row.UF, normalizeText(row.MUNICIPIO), row.SiteID.toUpperCase(), row.Tech].join('|');
    if (seen.has(key)) return;
    seen.add(key);
    out.push(row);
  });
  out.sort((a, b) =>
    a.UF.localeCompare(b.UF) ||
    a.MUNICIPIO.localeCompare(b.MUNICIPIO) ||
    a.SiteID.localeCompare(b.SiteID) ||
    a.Tech.localeCompare(b.Tech)
  );
  return out;
}

function mergeSiteListRows(existingRows, newRows) {
  return dedupeAndSortSiteRows([...(existingRows || []), ...(newRows || [])]);
}

function getAvailableUfsFromSiteList() {
  if (!siteListLoadedFromFile) return AVAILABLE_UFS.slice();
  const fromData = [...new Set(siteListData.map(r => (r.UF || '').toUpperCase().trim()).filter(Boolean))].sort();
  return fromData.length ? fromData : AVAILABLE_UFS.slice();
}

function refreshUfSelectOptions() {
  const ufSelect = document.getElementById('scope-uf-select');
  if (!ufSelect) return;
  const previous = (ufSelect.value || '').trim().toUpperCase();
  const ufs = getAvailableUfsFromSiteList();
  ufSelect.innerHTML = '<option value="">-- Use selected UF(s) --</option>' + ufs.map(u => `<option value="${u}">${u}</option>`).join('');
  if (previous && ufs.includes(previous)) ufSelect.value = previous;
}

function refreshScopeUfControls() {
  renderUfs();
  refreshUfSelectOptions();
  updateMunicipalityDatalist();
}

function loadSiteListFile() {
  const input = document.getElementById('site-list-file');
  const file = input && input.files[0];
  if (!file) {
    showEnmResult('warning', 'Choose a site list file first.');
    return;
  }
  const reader = new FileReader();
  reader.onload = function () {
    siteListData = dedupeAndSortSiteRows(parseSiteListTSV(reader.result));
    siteListLoadedFromFile = siteListData.length > 0;
    const statusEl = document.getElementById('site-list-status');
    if (statusEl) statusEl.innerHTML = `<span class="text-success">Loaded ${siteListData.length} sites.</span>`;
    refreshScopeUfControls();
    showEnmResult('success', `Site list loaded: ${siteListData.length} sites.`);
  };
  reader.readAsText(file, 'UTF-8'); // file was saved as UTF-8 (with BOM when downloaded from tool)
}

function getScope() {
  const r = document.querySelector('input[name="scope"]:checked');
  return (r && r.value) || 'uf';
}

function getSitesString() {
  const scope = getScope();
  if (scope === 'uf') {
    const ufs = getSelectedUfs();
    return ufs.map(uf => `*_${uf}`).join(';');
  }
  if (scope === 'list') {
    const ta = document.getElementById('scope-list-textarea');
    const text = (ta && ta.value || '').trim();
    const sites = text.split(/[\n;,]+/).map(s => s.trim()).filter(Boolean);
    return [...new Set(sites)].join(';');
  }
  if (scope === 'municipality') {
    const ufSelectedInCity = (document.getElementById('scope-uf-select') && document.getElementById('scope-uf-select').value || '').trim().toUpperCase();
    const selectedUfs = [...new Set([...getSelectedUfs(), ...(ufSelectedInCity ? [ufSelectedInCity] : [])])];
    const mun = (document.getElementById('scope-municipality-input') && document.getElementById('scope-municipality-input').value || '').trim();
    const selectedCitiesNorm = selectedMunicipalities.map(normalizeText);
    const lte = document.getElementById('scope-tech-lte') && document.getElementById('scope-tech-lte').checked;
    const nr = document.getElementById('scope-tech-nr') && document.getElementById('scope-tech-nr').checked;
    if (!selectedUfs.length) return '';
    if (!selectedCitiesNorm.length && !mun) return '';
    const filtered = siteListData.filter(r => {
      if (!selectedUfs.includes((r.UF || '').toUpperCase())) return false;
      if (selectedCitiesNorm.length) {
        if (!selectedCitiesNorm.includes(normalizeText(r.MUNICIPIO))) return false;
      } else if (!normalizeText(r.MUNICIPIO).includes(normalizeText(mun))) {
        return false;
      }
      const tech = (r.Tech || '').toUpperCase();
      if (tech === 'LTE' && !lte) return false;
      if (tech === 'NR' && !nr) return false;
      return true;
    });
    const ids = [...new Set(filtered.map(r => (r.SiteID || '').trim()).filter(Boolean))];
    return ids.join(';');
  }
  return '';
}

function updateScopePanels() {
  const scope = getScope();
  document.getElementById('scope-uf-panel').style.display = scope === 'uf' ? 'block' : 'none';
  document.getElementById('scope-municipality-panel').style.display = scope === 'municipality' ? 'block' : 'none';
  document.getElementById('scope-list-panel').style.display = scope === 'list' ? 'block' : 'none';
  if (scope === 'municipality') updateMunicipalityCount();
}

function updateMunicipalityCount() {
  const s = getSitesString();
  const count = s ? s.split(';').filter(Boolean).length : 0;
  const el = document.getElementById('scope-municipality-count');
  if (el) el.textContent = count ? `${count} site(s) selected.` : 'Select UF(s) and add one or more cities.';
}

function pruneSelectedMunicipalities(selectedUfs) {
  if (!selectedMunicipalities.length) return;
  if (!selectedUfs.length) return;
  const kept = selectedMunicipalities.filter(city =>
    siteListData.some(r =>
      selectedUfs.includes((r.UF || '').toUpperCase()) &&
      normalizeText(r.MUNICIPIO) === normalizeText(city)
    )
  );
  selectedMunicipalities = kept;
}

function renderSelectedMunicipalities() {
  const box = document.getElementById('municipality-selected');
  if (!box) return;
  if (!selectedMunicipalities.length) {
    box.innerHTML = '';
    return;
  }
  const chips = selectedMunicipalities.map(c => (
    `<span class="badge text-bg-primary me-1 mb-1">${c} ` +
    `<button type="button" class="btn-close btn-close-white ms-1 city-remove-btn" aria-label="Remove" data-city="${c}" style="font-size:0.55rem;"></button></span>`
  )).join('');
  box.innerHTML = `<div class="mb-1">${chips}</div><button type="button" class="btn btn-outline-secondary btn-sm" id="btn-clear-cities">Clear cities</button>`;
  box.querySelectorAll('.city-remove-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      const city = btn.getAttribute('data-city') || '';
      selectedMunicipalities = selectedMunicipalities.filter(c => normalizeText(c) !== normalizeText(city));
      renderSelectedMunicipalities();
      updateMunicipalityCount();
    });
  });
  const clearBtn = document.getElementById('btn-clear-cities');
  if (clearBtn) {
    clearBtn.addEventListener('click', () => {
      selectedMunicipalities = [];
      renderSelectedMunicipalities();
      updateMunicipalityCount();
    });
  }
}

function addMunicipalitySelection(city) {
  const c = (city || '').trim();
  if (!c) return;
  if (selectedMunicipalities.some(x => normalizeText(x) === normalizeText(c))) return;
  selectedMunicipalities.push(c);
  selectedMunicipalities.sort((a, b) => a.localeCompare(b));
  const input = document.getElementById('scope-municipality-input');
  if (input) input.value = '';
  renderSelectedMunicipalities();
  updateMunicipalityDatalist();
}

function getSelectedUfsForCityScope() {
  const ufSelectedInCity = (document.getElementById('scope-uf-select') && document.getElementById('scope-uf-select').value || '').trim().toUpperCase();
  return [...new Set([...getSelectedUfs(), ...(ufSelectedInCity ? [ufSelectedInCity] : [])])];
}

function resolveCityCandidate(rawQuery) {
  const q = (rawQuery || '').trim();
  if (!q) return '';
  const selectedUfs = getSelectedUfsForCityScope();
  const cities = [...new Set(
    siteListData
      .filter(r => !selectedUfs.length || selectedUfs.includes((r.UF || '').toUpperCase()))
      .map(r => (r.MUNICIPIO || '').trim())
      .filter(Boolean)
  )];
  const nq = normalizeText(q);
  const exact = cities.find(c => normalizeText(c) === nq);
  if (exact) return exact;
  const startsWithList = cities.filter(c => normalizeText(c).startsWith(nq));
  if (startsWithList.length) {
    startsWithList.sort((a, b) => a.length - b.length || a.localeCompare(b));
    return startsWithList[0];
  }
  const contains = cities.find(c => normalizeText(c).includes(nq));
  if (contains) return contains;
  return q;
}

function updateMunicipalityDatalist() {
  const ufSelectedInCity = (document.getElementById('scope-uf-select') && document.getElementById('scope-uf-select').value || '').trim().toUpperCase();
  const selectedUfs = [...new Set([...getSelectedUfs(), ...(ufSelectedInCity ? [ufSelectedInCity] : [])])];
  pruneSelectedMunicipalities(selectedUfs);
  renderSelectedMunicipalities();
  const q = (document.getElementById('scope-municipality-input') && document.getElementById('scope-municipality-input').value || '').trim();
  const list = document.getElementById('municipality-datalist');
  const sug = document.getElementById('municipality-suggestions');
  if (!list) return;
  list.innerHTML = '';
  if (sug) sug.innerHTML = '';
  if (!selectedUfs.length || siteListData.length === 0) {
    updateMunicipalityCount();
    return;
  }
  const nq = normalizeText(q);
  const allCities = [...new Set(
    siteListData
      .filter(r => selectedUfs.includes((r.UF || '').toUpperCase()))
      .map(r => (r.MUNICIPIO || '').trim())
      .filter(Boolean)
  )];
  const startsWith = allCities.filter(c => normalizeText(c).startsWith(nq)).sort();
  const contains  = allCities.filter(c => !normalizeText(c).startsWith(nq) && normalizeText(c).includes(nq)).sort();
  const matches = nq ? [...startsWith, ...contains] : allCities.sort();
  matches.slice(0, 100).forEach(m => {
    const opt = document.createElement('option');
    opt.value = m;
    list.appendChild(opt);
  });
  if (sug) {
    const quick = matches.slice(0, 12);
    if (quick.length) {
      sug.innerHTML = quick.map(m => `<button type="button" class="btn btn-outline-secondary btn-sm me-1 mb-1 mun-suggest-btn" data-city="${m}">${m}</button>`).join('');
      sug.querySelectorAll('.mun-suggest-btn').forEach(btn => {
        btn.addEventListener('click', () => addMunicipalitySelection(btn.getAttribute('data-city') || ''));
      });
    }
  }
  updateMunicipalityCount();
}

// ---------- ENM rows ----------
function renderEnmRows() {
  const tbody = document.getElementById('enm-rows');
  if (!tbody) return;
  tbody.innerHTML = ENM_IDS.map(id => `
    <tr>
      <td class="align-middle"><span class="fw-bold">${id}</span></td>
      <td class="text-center align-middle">
        <input class="form-check-input" type="checkbox" id="enm-include-${id}" data-enm-id="${id}" title="Include this ENM in dump">
      </td>
      <td class="align-middle">
        <input type="text" class="form-control form-control-sm" id="enm-username-${id}" placeholder="Leave blank if not used">
      </td>
      <td class="align-middle">
        <input type="password" class="form-control form-control-sm" id="enm-password-${id}" placeholder="Password">
      </td>
    </tr>
  `).join('');
}

/** Retorna lista de ENMs selecionados para dump (incluir marcado e username preenchido). */
function getSelectedEnms() {
  const list = [];
  ENM_IDS.forEach(id => {
    const include = document.getElementById(`enm-include-${id}`);
    const username = (document.getElementById(`enm-username-${id}`) || {}).value.trim();
    const password = (document.getElementById(`enm-password-${id}`) || {}).value;
    if (include && include.checked && username) {
      list.push({
        id,
        nameShort: enmShortName(id),
        url: ENM_SERVERS[id],
        username,
        password
      });
    }
  });
  return list;
}

/** All ENM form data (for saving in profile). */
function getEnmFormData() {
  const enms = {};
  ENM_IDS.forEach(id => {
    const u = document.getElementById(`enm-username-${id}`);
    const p = document.getElementById(`enm-password-${id}`);
    enms[id] = {
      username: u ? u.value.trim() : '',
      password: p ? p.value : ''
    };
  });
  return enms;
}

function setEnmFormData(enms) {
  if (!enms) return;
  ENM_IDS.forEach(id => {
    const cred = enms[id];
    if (!cred) return;
    const u = document.getElementById(`enm-username-${id}`);
    const p = document.getElementById(`enm-password-${id}`);
    if (u) u.value = cred.username || '';
    if (p) p.value = cred.password || '';
  });
}

// ---------- Profiles (localStorage): credenciais por ENM ----------
function loadProfilesData() {
  try {
    const raw = localStorage.getItem(STORAGE_PROFILES);
    return raw ? JSON.parse(raw) : { profiles: [], last_used_profile: null };
  } catch {
    return { profiles: [], last_used_profile: null };
  }
}

function saveProfilesData(data) {
  try {
    localStorage.setItem(STORAGE_PROFILES, JSON.stringify(data));
  } catch (e) {
    showEnmResult('danger', 'Could not save profiles.');
  }
}

function loadEnmProfiles() {
  const data = loadProfilesData();
  const sel = document.getElementById('enm-profile-select');
  if (!sel) return;
  const currentVal = sel.value;
  sel.innerHTML = '<option value="">-- Profile --</option>';
  (data.profiles || []).forEach(p => {
    const opt = document.createElement('option');
    opt.value = p.name;
    opt.textContent = p.name;
    sel.appendChild(opt);
  });
  if (data.last_used_profile && data.profiles.some(p => p.name === data.last_used_profile)) {
    sel.value = data.last_used_profile;
    const profile = data.profiles.find(p => p.name === data.last_used_profile);
    if (profile) applyProfileToForm(profile);
  } else if (currentVal) sel.value = currentVal;
}

function applyProfileToForm(profile) {
  setEnmFormData(profile.enms);
  const o = document.getElementById('enm-output-dir');
  if (o) {
    o.value = profile.output_dir || profile.dump_output_dir || o.value;
    var v = o.value.trim();
    if (v) try { localStorage.setItem(STORAGE_LAST_OUTPUT_DIR, v); } catch (_) {}
  }
}

function saveEnmProfile() {
  let name = document.getElementById('enm-profile-select').value;
  if (!name) {
    name = prompt('Profile name:');
    if (!name) return;
  }
  const enms = getEnmFormData();
  const outputDir = document.getElementById('enm-output-dir').value.trim();
  const data = loadProfilesData();
  const profile = { name, enms, output_dir: outputDir };
  let profiles = data.profiles || [];
  const idx = profiles.findIndex(p => p.name === name);
  if (idx >= 0) profiles[idx] = profile;
  else profiles.push(profile);
  data.profiles = profiles;
  data.last_used_profile = name;
  saveProfilesData(data);
  loadEnmProfiles();
  showEnmResult('success', `Profile "${name}" saved.`);
}

function deleteEnmProfile() {
  const name = document.getElementById('enm-profile-select').value;
  if (!name) {
    showEnmResult('warning', 'Select a profile.');
    return;
  }
  if (!confirm(`Delete profile "${name}"?`)) return;
  const data = loadProfilesData();
  data.profiles = (data.profiles || []).filter(p => p.name !== name);
  if (data.last_used_profile === name) data.last_used_profile = null;
  saveProfilesData(data);
  loadEnmProfiles();
  setEnmFormData({ ENMBARA: {}, ENMBARB: {}, ENMCTPB: {}, ENMCTPA: {} });
  showEnmResult('info', `Profile "${name}" deleted.`);
}

// ---------- UF Selection ----------
function renderUfs() {
  const container = document.getElementById('uf-checkboxes');
  if (!container) return;
  const current = new Set(getSelectedUfs());
  const ufs = getAvailableUfsFromSiteList();
  container.innerHTML = ufs.map(uf => `
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="checkbox" id="uf-${uf}" value="${uf}" ${current.has(uf) ? 'checked' : ''}>
      <label class="form-check-label small" for="uf-${uf}">${uf}</label>
    </div>
  `).join('');
  container.querySelectorAll('input[type="checkbox"]').forEach(cb => {
    cb.addEventListener('change', updateMunicipalityDatalist);
  });
}

function getSelectedUfs() {
  const values = [];
  document.querySelectorAll('#uf-checkboxes input[type="checkbox"]:checked').forEach(cb => values.push(cb.value));
  return values;
}

function selectAllUfs() {
  document.querySelectorAll('#uf-checkboxes input[type="checkbox"]').forEach(cb => { cb.checked = true; });
  updateMunicipalityDatalist();
}

function clearAllUfs() {
  document.querySelectorAll('#uf-checkboxes input[type="checkbox"]').forEach(cb => { cb.checked = false; });
  updateMunicipalityDatalist();
}

// ---------- MO Selection ----------
function renderMoDefaultList() {
  const container = document.getElementById('mo-default-list');
  if (!container) return;
  container.innerHTML = DEFAULT_MOS.map(mo => `
    <div class="form-check form-check-inline py-1 mo-item" style="font-size: 0.82rem; min-width: 12rem;" data-mo-name="${mo.id.toLowerCase()}">
      <input class="form-check-input mo-default-cb" type="checkbox" id="mo-cb-${mo.id}" data-mo-id="${mo.id}">
      <label class="form-check-label" for="mo-cb-${mo.id}"><code>${mo.id}</code></label>
    </div>
  `).join('');
  container.addEventListener('change', updateMoCount);
}

function getSelectedMos() {
  const mos = [];
  document.querySelectorAll('.mo-default-cb:checked').forEach(cb => {
    const id = cb.getAttribute('data-mo-id');
    if (id) mos.push(id);
  });
  customMos.forEach(mo => {
    const id = mo.replace(/\.\*;?$/, '').replace(/;$/, '');
    if (id && !mos.includes(id)) mos.push(id);
  });
  return mos;
}

function setAllMoCheckboxes(checked) {
  document.querySelectorAll('.mo-default-cb').forEach(cb => { cb.checked = !!checked; });
  updateMoCount();
}

function selectMoB() {
  document.querySelectorAll('.mo-default-cb').forEach(cb => {
    const id = cb.getAttribute('data-mo-id');
    cb.checked = MOB_MOS.some(m => m.toLowerCase() === (id || '').toLowerCase());
  });
  updateMoCount();
}

function filterMoList(query) {
  const q = (query || '').toLowerCase().trim();
  document.querySelectorAll('#mo-default-list .mo-item').forEach(el => {
    const name = el.getAttribute('data-mo-name') || '';
    el.style.display = (!q || name.includes(q)) ? '' : 'none';
  });
}

function updateMoCount() {
  const total = document.querySelectorAll('.mo-default-cb').length;
  const selected = document.querySelectorAll('.mo-default-cb:checked').length;
  const badge = document.getElementById('mo-count-badge');
  if (badge) badge.textContent = `${selected} / ${total}`;
}

function addCustomMo() {
  const input = document.getElementById('mo-custom-input');
  const value = (input && input.value || '').trim();
  if (!value) return;
  if (customMos.includes(value) || DEFAULT_MOS.some(m => m.pattern === value || m.id === value)) {
    showEnmResult('warning', 'This MO is already included.');
    return;
  }
  customMos.push(value);
  input.value = '';
  renderCustomMos();
}

function removeCustomMo(index) {
  customMos.splice(index, 1);
  renderCustomMos();
}

function renderCustomMos() {
  const container = document.getElementById('mo-custom-list');
  if (!container) return;
  if (customMos.length === 0) {
    container.innerHTML = '';
    return;
  }
  container.innerHTML = customMos.map((mo, i) => `
    <div class="d-flex align-items-center gap-2 py-1" style="font-size: 0.82rem;">
      <i class="bi bi-plus-circle-fill text-primary" style="font-size: 0.7rem;"></i>
      <code class="text-dark">${mo}</code>
      <button class="btn btn-link btn-sm text-danger p-0 ms-auto" type="button" data-remove-mo="${i}" title="Remove">
        <i class="bi bi-x-lg" style="font-size: 0.7rem;"></i>
      </button>
    </div>
  `).join('');
  container.querySelectorAll('[data-remove-mo]').forEach(btn => {
    btn.addEventListener('click', () => removeCustomMo(parseInt(btn.getAttribute('data-remove-mo'), 10)));
  });
}

// ---------- Command generation ----------
function generateEnmCommand() {
  const scope = getScope();
  const sitesString = getSitesString();
  if (!sitesString) {
    if (scope === 'uf') showEnmResult('warning', 'Select at least one UF.');
    else if (scope === 'municipality') showEnmResult('warning', 'Load site list, then select UF(s) and city.');
    else showEnmResult('warning', 'Enter at least one site ID.');
    return;
  }
  const now = new Date();
  const timestamp = now.getFullYear() +
    String(now.getMonth() + 1).padStart(2, '0') +
    String(now.getDate()).padStart(2, '0') + '_' +
    String(now.getHours()).padStart(2, '0') +
    String(now.getMinutes()).padStart(2, '0') +
    String(now.getSeconds()).padStart(2, '0');
  const jobName = `downloader_${timestamp}`;
  const command = `cmedit export -n ${sitesString} --filetype 3GPP -jn ${jobName} -f file:mos_downloader.txt`;
  const textarea = document.getElementById('enm-command');
  if (textarea) {
    textarea.value = command;
    textarea.removeAttribute('readonly');
  }
  const selected = getSelectedEnms();
  const msg = selected.length > 0
    ? `Command generated. Each selected ENM will use its own job name (e.g. BARA_${timestamp}). (${selected.length} ENM(s) selected.)`
    : `Command generated. Job: ${jobName}. Check ENMs and fill user/password to run on multiple ENMs.`;
  showEnmResult('success', msg);
}

function copyEnmCommand() {
  const cmd = document.getElementById('enm-command');
  if (!cmd || !cmd.value.trim()) {
    showEnmResult('warning', 'Generate the command first.');
    return;
  }
  cmd.select();
  navigator.clipboard.writeText(cmd.value).then(() => {
    showEnmResult('info', 'Command copied.');
  }).catch(() => {
    showEnmResult('warning', 'Copy manually.');
  });
}

// ---------- Export JSON for Python script ----------
function exportForScript() {
  if (!getSitesString()) {
    showEnmResult('warning', 'Select scope (UF, city, or site list) and generate command before export.');
    return;
  }
  if (getSelectedEnms().length === 0) {
    showEnmResult('warning', 'Check and fill user/password for at least one ENM.');
    return;
  }
  if (!document.getElementById('enm-command').value.trim()) {
    showEnmResult('warning', 'Generate the command before export.');
    return;
  }
  const config = getExportConfig();
  const blob = new Blob([JSON.stringify(config, null, 2)], { type: 'application/json' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `downloader_dump_config_${new Date().toISOString().slice(0, 10)}_${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(a.href);
  showEnmResult('success', `Config saved. You can run run_dump.bat <this file> in a terminal, or use Execute Dump when the tool is opened via START_DOWNLOADER.bat.`);
  appendLog(`[${new Date().toLocaleTimeString()}] Config exported. Run run_dump.bat <config.json> in a terminal, or use Execute Dump if you opened the tool with START_DOWNLOADER.bat.`);
}

/** Build config object for export or for API (same shape as exported JSON). */
function getExportConfig() {
  const sitesString = getSitesString();
  const selectedEnms = getSelectedEnms();
  const commandTemplate = document.getElementById('enm-command').value.trim();
  const outputDir = document.getElementById('enm-output-dir').value.trim();
  return {
    version: 1,
    output_dir: outputDir || 'C:/eNB_Fake/data/input',
    mos_file: 'mos_downloader.txt',
    command_template: commandTemplate,
    sites_string: sitesString,
    scope: getScope(),
    selected_ufs: getScope() === 'uf' ? getSelectedUfs() : [],
    selected_mos: getSelectedMos(),
    enms: selectedEnms.map(e => ({
      id: e.id,
      name_short: e.nameShort,
      url: e.url,
      username: e.username,
      password: e.password
    })),
    exported_at: new Date().toISOString()
  };
}

// ---------- Logs panel ----------
function appendLog(text) {
  const el = document.getElementById('dump-logs');
  if (!el) return;
  const line = (typeof text === 'string' ? text : '') + '\n';
  el.value += line;
  el.scrollTop = el.scrollHeight;
}

function clearLogs() {
  const el = document.getElementById('dump-logs');
  if (el) el.value = '';
}

/** Get path string from a folder file input (webkitdirectory). Browsers may return C:\fakepath\Name. */
function getPathFromFolderInput(inputEl) {
  if (!inputEl || !inputEl.files || inputEl.files.length === 0) return '';
  const first = inputEl.files[0];
  // Desktop shells may expose absolute path on File objects.
  if (first && first.path) {
    const dir = dirnamePath(first.path);
    if (dir) return dir.replace(/\\/g, '/');
  }
  if (inputEl.value && !/fakepath/i.test(inputEl.value)) {
    return inputEl.value.replace(/\\/g, '/');
  }
  if (first && first.webkitRelativePath) {
    const seg = first.webkitRelativePath.split(/[/\\]/)[0];
    return seg || '';
  }
  return '';
}

/** Load saved path into input and save on change/blur so paths are remembered. */
function bindPathStorage(inputId, storageKey) {
  const el = document.getElementById(inputId);
  if (!el) return;
  try {
    const saved = localStorage.getItem(storageKey);
    if (saved) el.value = saved;
  } catch (_) {}
  el.addEventListener('change', function () {
    const v = this.value.trim();
    if (v) try { localStorage.setItem(storageKey, v); } catch (_) {}
  });
  el.addEventListener('blur', function () {
    const v = this.value.trim();
    if (v) try { localStorage.setItem(storageKey, v); } catch (_) {}
  });
}

/** Build parser pipeline payload from current form state. */
function getParserPayload(overrideInputDir) {
  const inputDir = overrideInputDir || document.getElementById('parser-input-dir').value.trim();
  const outputDir = document.getElementById('parser-output-dir').value.trim();
  const customizeTxts = document.getElementById('chk-customize-txts').checked;
  const cellrefDir = (document.getElementById('parser-cellref-dir') || {}).value || 'C:/Downloader/cellref';
  const enrichedDir = (document.getElementById('parser-enriched-dir') || {}).value || 'C:/Downloader/data/enriched';
  return {
    input_dir: inputDir,
    output_dir: outputDir || inputDir,
    customize_txts: customizeTxts,
    cellref_dir: cellrefDir.trim(),
    enriched_dir: enrichedDir.trim()
  };
}

/** Run full parser pipeline via streaming API. */
let _runParserAbort = null;

async function runParserPipeline() {
  const payload = getParserPayload();
  const resultEl = document.getElementById('parser-result');
  const logArea = document.getElementById('parser-log-area');
  const btnCancel = document.getElementById('btn-run-parser-cancel');
  if (!resultEl || !logArea) return;

  if (!payload.input_dir) {
    resultEl.style.display = 'block';
    logArea.value = 'Enter Input Directory (folder with ZIP or XML files).';
    return;
  }

  resultEl.style.display = 'block';
  logArea.value = 'Starting parser pipeline...\n';
  logArea.value += 'Input:    ' + payload.input_dir + '\n';
  logArea.value += 'Output:   ' + payload.output_dir + '\n';
  if (payload.customize_txts) logArea.value += 'Enriched: ' + payload.enriched_dir + '\n';
  logArea.value += '\n';

  const btn = document.getElementById('btn-run-parser');
  if (btn) { btn.disabled = true; btn.innerHTML = '<i class="bi bi-hourglass-split"></i> Running...'; }
  if (btnCancel) { btnCancel.disabled = false; }

  const controller = new AbortController();
  _runParserAbort = controller;

  try {
    const response = await fetch('http://127.0.0.1:8765/api/run-parser-pipeline', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
      signal: controller.signal
    });

    if (!response.ok) {
      const errText = await response.text();
      logArea.value += '\nServer error: ' + response.status + ' ' + (errText || response.statusText);
      return;
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';
    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split(/\r?\n/);
      buffer = lines.pop() || '';
      for (const line of lines) {
        logArea.value += line + '\n';
        logArea.scrollTop = logArea.scrollHeight;
      }
    }
    if (buffer.trim()) logArea.value += buffer + '\n';
    logArea.scrollTop = logArea.scrollHeight;

  } catch (err) {
    if (err.name === 'AbortError') {
      logArea.value += '\n--- CANCELLED BY USER ---\n';
    } else {
      logArea.value += '\nError: ' + (err.message || String(err)) + '\nMake sure the server is running (START_DOWNLOADER.bat).\n';
    }
  } finally {
    _runParserAbort = null;
    if (btn) { btn.disabled = false; btn.innerHTML = '<i class="bi bi-play-fill"></i> Run Parser'; }
    if (btnCancel) { btnCancel.disabled = true; }
  }
}

function cancelParserPipeline() {
  if (_runParserAbort) {
    _runParserAbort.abort();
    _runParserAbort = null;
  }
}

/** Run dump: if server is available, POST config and stream logs; otherwise show instructions in log panel. */
async function executeDump() {
  const cmd = document.getElementById('enm-command').value.trim();
  const selected = getSelectedEnms();
  if (!cmd) {
    showEnmResult('warning', 'Generate the command first.');
    return;
  }
  if (selected.length === 0) {
    showEnmResult('warning', 'Check and fill user/password for at least one ENM.');
    return;
  }
  if (!getSitesString()) {
    showEnmResult('warning', 'Select scope (UF, city, or site list) and generate command first.');
    return;
  }

  const config = getExportConfig();
  const parserInputEl = document.getElementById('parser-input-dir');
  if (parserInputEl && config.output_dir) {
    parserInputEl.value = config.output_dir;
    try { localStorage.setItem(STORAGE_PARSER_INPUT, config.output_dir); } catch (_) {}
  }
  appendLog(`[${new Date().toLocaleTimeString()}] Execute Dump: ${selected.length} ENM(s) selected.`);
  appendLog(`[${new Date().toLocaleTimeString()}] Output folder: ${config.output_dir}`);
  appendLog(`[${new Date().toLocaleTimeString()}] Parser input synced to: ${config.output_dir}`);

  const apiUrl = 'http://127.0.0.1:8765/api/run-dump';
  appendLog('Calling server...');
  showEnmResult('info', 'Running dump - watch the Logs panel below.');

  try {
    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(config)
    });
    if (!response.ok) {
      const errText = await response.text();
      appendLog('Server error: ' + response.status + ' ' + (errText || response.statusText));
      showEnmResult('danger', 'Server error: ' + response.status);
      return;
    }
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';
    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split(/\r?\n/);
      buffer = lines.pop() || '';
      for (const line of lines) {
        if (line.trim()) appendLog(line);
      }
    }
    if (buffer.trim()) appendLog(buffer);
    appendLog(`[${new Date().toLocaleTimeString()}] Done.`);
    showEnmResult('success', 'Dump finished. Check the Logs panel.');
  } catch (err) {
    appendLog('Error: ' + (err.message || String(err)));
    appendLog('Run START_DOWNLOADER.bat to open the tool with the server, then try Execute Dump again.');
    showEnmResult('danger', 'Could not run dump. Open the tool with START_DOWNLOADER.bat and try again.');
  }
}

// ---------- UI helpers ----------
function showEnmResult(type, message) {
  const el = document.getElementById('enm-result');
  if (!el) return;
  el.style.display = 'block';
  el.className = `alert alert-${type} mt-2`;
  el.innerHTML = message;
}

function updateStatusBar() {
  const el = document.getElementById('status-timestamp');
  if (el) {
    const now = new Date();
    el.textContent = now.toLocaleString('en-GB', {
      day: '2-digit', month: '2-digit', year: 'numeric',
      hour: '2-digit', minute: '2-digit', second: '2-digit'
    });
  }
}

// ---------- Run All (Dump + Parser) ----------
let _runAllAbort = null;

/** Returns { content: string } - the full streamed output for caller to inspect. */
async function _streamToLog(logEl, phaseEl, url, body, phaseName) {
  if (phaseEl) phaseEl.textContent = phaseName;
  logEl.value += `\n${'='.repeat(50)}\n  ${phaseName}\n${'='.repeat(50)}\n`;
  logEl.scrollTop = logEl.scrollHeight;

  const controller = new AbortController();
  _runAllAbort = controller;
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
    signal: controller.signal
  });

  if (!response.ok) {
    const errText = await response.text();
    logEl.value += 'Server error: ' + response.status + ' ' + (errText || '') + '\n';
    throw new Error('Server error ' + response.status);
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';
  let fullContent = '';
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    const chunk = decoder.decode(value, { stream: true });
    buffer += chunk;
    fullContent += chunk;
    const lines = buffer.split(/\r?\n/);
    buffer = lines.pop() || '';
    for (const line of lines) {
      logEl.value += line + '\n';
      logEl.scrollTop = logEl.scrollHeight;
    }
  }
  if (buffer.trim()) {
    logEl.value += buffer + '\n';
    fullContent += buffer + '\n';
  }
  logEl.scrollTop = logEl.scrollHeight;
  return { content: fullContent };
}

/** Returns true if Phase 1 (ENM Dump) succeeded (at least one ENM produced files). */
function _dumpPhaseSucceeded(content) {
  if (!content) return false;
  if (/Process exited with code [1-9]\d*/.test(content)) return false;
  return /OK\s+\w+:\s*Success/i.test(content);
}

async function runAll() {
  const logEl = document.getElementById('run-all-log');
  const phaseEl = document.getElementById('run-all-phase');
  const statusEl = document.getElementById('run-all-status');
  const btnClose = document.getElementById('btn-run-all-close');
  const btnCancel = document.getElementById('btn-run-all-cancel');
  const btnRunAll = document.getElementById('btn-run-all');

  // Validate dump prerequisites
  generateEnmCommand();
  const cmd = document.getElementById('enm-command').value.trim();
  const selected = getSelectedEnms();
  if (!cmd || selected.length === 0 || !getSitesString()) {
    showEnmResult('warning', 'Configure ENM connection, scope, and generate command before Run All.');
    return;
  }

  const outputDir = document.getElementById('enm-output-dir').value.trim();
  if (!outputDir) {
    showEnmResult('warning', 'Set Output Directory before running.');
    return;
  }

  // Open modal
  const modal = new bootstrap.Modal(document.getElementById('runAllModal'));
  logEl.value = `[${new Date().toLocaleTimeString()}] Run All started.\n`;
  logEl.value += `ENMs: ${selected.map(e => e.id).join(', ')}\n`;
  logEl.value += `Output: ${outputDir}\n`;
  if (btnClose) btnClose.disabled = true;
  if (btnCancel) btnCancel.disabled = false;
  if (btnRunAll) btnRunAll.disabled = true;
  if (statusEl) statusEl.textContent = 'Running...';
  modal.show();

  const startTime = Date.now();

  // Cancel handler
  if (btnCancel) {
    btnCancel.onclick = () => {
      if (_runAllAbort) { _runAllAbort.abort(); _runAllAbort = null; }
      logEl.value += '\n--- CANCELLED BY USER ---\n';
      if (statusEl) statusEl.textContent = 'Cancelled.';
      if (btnClose) btnClose.disabled = false;
      if (btnCancel) btnCancel.disabled = true;
      if (btnRunAll) btnRunAll.disabled = false;
    };
  }

  try {
    // Phase 1: Dump
    const config = getExportConfig();
    const phase1Result = await _streamToLog(logEl, phaseEl, 'http://127.0.0.1:8765/api/run-dump', config, 'Phase 1: ENM Dump');

    if (!_dumpPhaseSucceeded(phase1Result.content)) {
      const elapsed = ((Date.now() - startTime) / 1000).toFixed(0);
      logEl.value += `\n[${new Date().toLocaleTimeString()}] Run All STOPPED: Phase 1 (ENM Dump) failed. Fix the dump error above and try again.\n`;
      if (phaseEl) phaseEl.textContent = 'Dump failed';
      if (statusEl) statusEl.textContent = `Dump failed (${elapsed}s). Parser skipped.`;
      return;
    }

    // Phase 2: Parser Pipeline (only runs if Phase 1 succeeded)
    const parserPayload = getParserPayload(outputDir);
    await _streamToLog(logEl, phaseEl, 'http://127.0.0.1:8765/api/run-parser-pipeline',
      parserPayload, 'Phase 2: XML Parser + TXT');

    const elapsed = ((Date.now() - startTime) / 1000).toFixed(0);
    logEl.value += `\n[${new Date().toLocaleTimeString()}] Run All COMPLETED in ${elapsed}s.\n`;
    if (phaseEl) phaseEl.textContent = 'Completed';
    if (statusEl) statusEl.textContent = `Completed in ${elapsed}s.`;

  } catch (err) {
    if (err.name === 'AbortError') return;
    logEl.value += '\nError: ' + (err.message || String(err)) + '\n';
    if (phaseEl) phaseEl.textContent = 'Error';
    if (statusEl) statusEl.textContent = 'Failed. Check log above.';
  } finally {
    _runAllAbort = null;
    if (btnClose) btnClose.disabled = false;
    if (btnCancel) btnCancel.disabled = true;
    if (btnRunAll) btnRunAll.disabled = false;
  }
}

// ---------- Init ----------
function init() {
  updateStatusBar();
  const statusTs = document.getElementById('status-timestamp');
  if (statusTs) setInterval(updateStatusBar, 1000);

  renderEnmRows();
  renderUfs();
  renderMoDefaultList();
  setAllMoCheckboxes(true);
  loadEnmProfiles();
  updateScopePanels();

  document.querySelectorAll('.scope-radio').forEach(r => {
    r.addEventListener('change', updateScopePanels);
  });
  const folderPathEl = document.getElementById('site-list-folder-path');
  if (folderPathEl) {
    bindPathStorage('site-list-folder-path', STORAGE_SITE_LIST_SAVE_DIR);
    if (!folderPathEl.value.trim()) {
      folderPathEl.value = 'C:/Downloader/cellref';
    }
    folderPathEl.addEventListener('change', () => { tryAutoLoadSiteListFromBaseDir(true); });
    folderPathEl.addEventListener('blur', () => { tryAutoLoadSiteListFromBaseDir(true); });
  }
  const folderPickerSiteListBase = document.getElementById('folder-picker-site-list-base');
  if (folderPickerSiteListBase && folderPathEl) {
    const btnBrowseSiteListBase = document.getElementById('btn-browse-site-list-base');
    if (btnBrowseSiteListBase) {
      btnBrowseSiteListBase.addEventListener('click', () => folderPickerSiteListBase.click());
    }
    folderPickerSiteListBase.addEventListener('change', function () {
      const path = getPathFromFolderInput(this);
      if (path) {
        folderPathEl.value = path;
        try { localStorage.setItem(STORAGE_SITE_LIST_SAVE_DIR, path); } catch (_) {}
        tryAutoLoadSiteListFromBaseDir(true);
      }
      this.value = '';
    });
  }
  const folderInput = document.getElementById('site-list-folder-input');
  const btnUpdateSiteList = document.getElementById('btn-update-site-list');
  if (btnUpdateSiteList && folderInput) {
    btnUpdateSiteList.addEventListener('click', async () => {
      if (siteListBusy) return;
      const existingFiles = folderInput.files;
      if (existingFiles && existingFiles.length > 0) {
        await updateSiteListFromFolder(existingFiles);
        return;
      }
      try {
        // More reliable than input.click() in some browsers/policies.
        if (typeof folderInput.showPicker === 'function') {
          await folderInput.showPicker();
        } else {
          folderInput.click();
        }
      } catch (_) {
        folderInput.click();
      }
    });
    folderInput.addEventListener('change', async function () {
      if (siteListBusy) return;
      const files = this.files;
      if (!files || !files.length) {
        showEnmResult('warning', 'No files selected. Choose one or more files to update site list.');
        return;
      }
      const inferredBase = inferBaseDirFromSelectedFiles(files);
      if (folderPathEl && inferredBase) {
        folderPathEl.value = inferredBase;
        try { localStorage.setItem(STORAGE_SITE_LIST_SAVE_DIR, inferredBase); } catch (_) {}
      }
      const names = Array.from(files).map(f => f.name).filter(Boolean);
      const preview = names.slice(0, 3).join(', ');
      const selectedLabel = names.length > 3
        ? `${names.length} files selected (${preview}, ...)`
        : `${names.length} files selected (${preview})`;
      showEnmResult('info', inferredBase
        ? `${selectedLabel}. Base dir detected: ${inferredBase}`
        : `${selectedLabel}. Base dir not auto-detected by browser; keeping current value. If needed, set Base dir using the folder button next to it.`);
      await updateSiteListFromFolder(files);
      this.value = '';
    });
  }
  const btnLoadSiteList = document.getElementById('btn-load-site-list');
  if (btnLoadSiteList) btnLoadSiteList.addEventListener('click', loadSiteListFile);
  const scopeUfSelect = document.getElementById('scope-uf-select');
  if (scopeUfSelect) scopeUfSelect.addEventListener('change', updateMunicipalityDatalist);
  const scopeMunInput = document.getElementById('scope-municipality-input');
  if (scopeMunInput) {
    scopeMunInput.addEventListener('input', updateMunicipalityDatalist);
    scopeMunInput.addEventListener('change', updateMunicipalityCount);
    scopeMunInput.addEventListener('focus', updateMunicipalityDatalist);
    scopeMunInput.addEventListener('keydown', (e) => {
      if (e.key !== 'Enter') return;
      e.preventDefault();
      const q = (scopeMunInput.value || '').trim();
      if (!q) return;
      addMunicipalitySelection(resolveCityCandidate(q));
    });
  }
  const btnAddCity = document.getElementById('btn-add-city');
  if (btnAddCity) {
    btnAddCity.addEventListener('click', () => {
      const input = document.getElementById('scope-municipality-input');
      if (!input) return;
      const q = (input.value || '').trim();
      if (!q) return;
      addMunicipalitySelection(resolveCityCandidate(q));
    });
  }
  document.getElementById('scope-tech-lte').addEventListener('change', updateMunicipalityDatalist);
  document.getElementById('scope-tech-nr').addEventListener('change', updateMunicipalityDatalist);

  // Remember all paths (load last used and save on change/blur)
  bindPathStorage('enm-output-dir', STORAGE_LAST_OUTPUT_DIR);
  bindPathStorage('parser-input-dir', STORAGE_PARSER_INPUT);
  bindPathStorage('parser-output-dir', STORAGE_PARSER_OUTPUT);
  bindPathStorage('parser-cellref-dir', STORAGE_PARSER_CELLREF);
  bindPathStorage('parser-enriched-dir', STORAGE_PARSER_ENRICHED);
  bindPathStorage('file-viewer-output-dir', STORAGE_FILE_VIEWER_OUTPUT);

  document.getElementById('enm-profile-select').addEventListener('change', function () {
    const name = this.value;
    if (!name) return;
    const data = loadProfilesData();
    const profile = (data.profiles || []).find(p => p.name === name);
    if (profile) applyProfileToForm(profile);
    data.last_used_profile = name;
    saveProfilesData(data);
  });

  document.getElementById('btn-save-profile').addEventListener('click', saveEnmProfile);
  document.getElementById('btn-delete-profile').addEventListener('click', deleteEnmProfile);
  document.getElementById('btn-uf-all').addEventListener('click', selectAllUfs);
  document.getElementById('btn-uf-clear').addEventListener('click', clearAllUfs);
  const btnMoSelectAll = document.getElementById('btn-mo-select-all');
  if (btnMoSelectAll) btnMoSelectAll.addEventListener('click', () => setAllMoCheckboxes(true));
  const btnMoClear = document.getElementById('btn-mo-clear');
  if (btnMoClear) btnMoClear.addEventListener('click', () => setAllMoCheckboxes(false));
  const btnMoMoB = document.getElementById('btn-mo-select-mob');
  if (btnMoMoB) btnMoMoB.addEventListener('click', selectMoB);
  const moSearchInput = document.getElementById('mo-search-input');
  if (moSearchInput) {
    moSearchInput.addEventListener('input', function () { filterMoList(this.value); });
  }
  const btnMoSearchClear = document.getElementById('btn-mo-search-clear');
  if (btnMoSearchClear) {
    btnMoSearchClear.addEventListener('click', function () {
      if (moSearchInput) { moSearchInput.value = ''; filterMoList(''); }
    });
  }
  document.getElementById('btn-add-mo').addEventListener('click', addCustomMo);
  document.getElementById('mo-custom-input').addEventListener('keydown', function (e) {
    if (e.key === 'Enter') { e.preventDefault(); addCustomMo(); }
  });
  document.getElementById('btn-generate-command').addEventListener('click', generateEnmCommand);
  document.getElementById('btn-copy-command').addEventListener('click', copyEnmCommand);

  document.getElementById('btn-execute-dump').addEventListener('click', executeDump);
  const btnClearLogs = document.getElementById('btn-clear-logs');
  if (btnClearLogs) btnClearLogs.addEventListener('click', clearLogs);

  // Folder picker: Output directory
  const folderPickerOutput = document.getElementById('folder-picker-output');
  const enmOutputDirEl = document.getElementById('enm-output-dir');
  if (folderPickerOutput && enmOutputDirEl) {
    document.getElementById('btn-browse-output').addEventListener('click', () => folderPickerOutput.click());
    folderPickerOutput.addEventListener('change', function () {
      const path = getPathFromFolderInput(this);
      if (path) {
        enmOutputDirEl.value = path;
        try { localStorage.setItem(STORAGE_LAST_OUTPUT_DIR, path); } catch (_) {}
      }
      this.value = '';
    });
  }

  // Folder picker: Parser input directory
  const folderPickerParserInput = document.getElementById('folder-picker-parser-input');
  const parserInputDirEl = document.getElementById('parser-input-dir');
  if (folderPickerParserInput && parserInputDirEl) {
    document.getElementById('btn-browse-parser-input').addEventListener('click', () => folderPickerParserInput.click());
    folderPickerParserInput.addEventListener('change', function () {
      const path = getPathFromFolderInput(this);
      if (path) {
        parserInputDirEl.value = path;
        try { localStorage.setItem(STORAGE_PARSER_INPUT, path); } catch (_) {}
      }
      this.value = '';
    });
  }

  // Folder picker: Parser output directory
  const folderPickerParserOutput = document.getElementById('folder-picker-parser-output');
  const parserOutputDirEl = document.getElementById('parser-output-dir');
  if (folderPickerParserOutput && parserOutputDirEl) {
    document.getElementById('btn-browse-parser-output').addEventListener('click', () => folderPickerParserOutput.click());
    folderPickerParserOutput.addEventListener('change', function () {
      const path = getPathFromFolderInput(this);
      if (path) {
        parserOutputDirEl.value = path;
        try { localStorage.setItem(STORAGE_PARSER_OUTPUT, path); } catch (_) {}
      }
      this.value = '';
    });
  }

  // Folder picker: Parser cellref directory
  const folderPickerParserCellref = document.getElementById('folder-picker-parser-cellref');
  const parserCellrefDirEl = document.getElementById('parser-cellref-dir');
  if (folderPickerParserCellref && parserCellrefDirEl) {
    document.getElementById('btn-browse-parser-cellref').addEventListener('click', () => folderPickerParserCellref.click());
    folderPickerParserCellref.addEventListener('change', function () {
      const path = getPathFromFolderInput(this);
      if (path) {
        parserCellrefDirEl.value = path;
        try { localStorage.setItem(STORAGE_PARSER_CELLREF, path); } catch (_) {}
      }
      this.value = '';
    });
  }

  // Folder picker: Parser enriched directory
  const folderPickerParserEnriched = document.getElementById('folder-picker-parser-enriched');
  const parserEnrichedDirEl = document.getElementById('parser-enriched-dir');
  if (folderPickerParserEnriched && parserEnrichedDirEl) {
    document.getElementById('btn-browse-parser-enriched').addEventListener('click', () => folderPickerParserEnriched.click());
    folderPickerParserEnriched.addEventListener('change', function () {
      const path = getPathFromFolderInput(this);
      if (path) {
        parserEnrichedDirEl.value = path;
        try { localStorage.setItem(STORAGE_PARSER_ENRICHED, path); } catch (_) {}
      }
      this.value = '';
    });
  }

  // Folder picker: File Viewer output directory
  const folderPickerFileViewerOutput = document.getElementById('folder-picker-file-viewer-output');
  const fileViewerOutputDirEl = document.getElementById('file-viewer-output-dir');
  if (folderPickerFileViewerOutput && fileViewerOutputDirEl) {
    document.getElementById('btn-browse-file-viewer-output').addEventListener('click', () => folderPickerFileViewerOutput.click());
    folderPickerFileViewerOutput.addEventListener('change', function () {
      const path = getPathFromFolderInput(this);
      if (path) {
        fileViewerOutputDirEl.value = path;
        try { localStorage.setItem(STORAGE_FILE_VIEWER_OUTPUT, path); } catch (_) {}
      }
      this.value = '';
    });
  }

  // "Enrich Files" checkbox: show/hide enrichment options, persist state
  const chkCustomize = document.getElementById('chk-customize-txts');
  const enrichGroup = document.getElementById('enrich-options-group');
  if (chkCustomize && enrichGroup) {
    try {
      const saved = localStorage.getItem(STORAGE_CUSTOMIZE_TXTS);
      if (saved === 'true') chkCustomize.checked = true;
    } catch (_) {}
    enrichGroup.style.display = chkCustomize.checked ? 'block' : 'none';
    chkCustomize.addEventListener('change', function () {
      enrichGroup.style.display = this.checked ? 'block' : 'none';
      try { localStorage.setItem(STORAGE_CUSTOMIZE_TXTS, String(this.checked)); } catch (_) {}
    });
  }

  // Parser pipeline button
  const btnRunParser = document.getElementById('btn-run-parser');
  if (btnRunParser) btnRunParser.addEventListener('click', runParserPipeline);
  const btnRunParserCancel = document.getElementById('btn-run-parser-cancel');
  if (btnRunParserCancel) btnRunParserCancel.addEventListener('click', cancelParserPipeline);

  const btnExport = document.getElementById('btn-export-script');
  if (btnExport) btnExport.addEventListener('click', exportForScript);

  // Run All button
  const btnRunAll = document.getElementById('btn-run-all');
  if (btnRunAll) btnRunAll.addEventListener('click', runAll);

  // Auto-load site list from Base dir on startup (if sites_list.txt exists)
  tryAutoLoadSiteListFromBaseDir(true);
}

document.addEventListener('DOMContentLoaded', init);

// Shut down the backend when the browser page/tab is closed
window.addEventListener('beforeunload', function () {
  navigator.sendBeacon('http://127.0.0.1:8765/api/shutdown');
});
